name = "worker-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[[kv_namespaces]]
binding = "Animal_Rescues_Rusty_KV"
id = "7883e81602324e04b5aadafcfa09f90b"
preview-id = "fa2ddae325754c8a881ef5ef5cfdbe40"

[build]
command = "cargo install -q worker-build && worker-build --release"
